# Generated by Django 6.0.6 on 2026-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('cell_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lon_min', models.IntegerField()),
                ('lat_min', models.IntegerField()),
                ('multiplier', models.FloatField(default=5.0)),
                ('strike_count_24h', models.IntegerField(default=0)),
                ('strike_count_1h', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightningStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('quality', models.CharField(max_length=20)),
                ('source', models.CharField(default='blitzortung', max_length=50)),
                ('grid_cell', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['grid_cell', 'timestamp'], name='lightning_l_grid_ce_a979fe_idx')],
            },
        ),
    ]
