# Generated by Django 6.0.6 on 2026-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrikeRollupMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField()),
                ('cell_id', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('bad', models.IntegerField(default=0)),
                ('latency_sum_ms', models.BigIntegerField(default=0)),
                ('latency_n', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['bucket'], name='lightning_s_bucket_1d2a25_idx'), models.Index(fields=['cell_id', 'bucket'], name='lightning_s_cell_id_930277_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'cell_id'), name='uniq_rollup_bucket_cell')],
            },
        ),
    ]
