# Generated by Django 6.0.6 on 2026-06-15 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0002_strikerollupminute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GridCell',
        ),
        migrations.RemoveIndex(
            model_name='lightningstrike',
            name='lightning_l_grid_ce_a979fe_idx',
        ),
        migrations.AddField(
            model_name='lightningstrike',
            name='received_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 6, 15, 10, 56, 22, 370740, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='lightningstrike',
            index=models.Index(fields=['timestamp'], name='lightning_l_timesta_4d8c37_idx'),
        ),
        migrations.RemoveField(
            model_name='lightningstrike',
            name='grid_cell',
        ),
    ]
