# Generated by Django 6.0.6 on 2026-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0003_delete_gridcell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('quality', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['country', '-received_at'], name='lightning_c_country_0c68d0_idx')],
            },
        ),
    ]
