# Generated by Cursor on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lightning", "0004_countrystrike"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityStrikeAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city_id", models.CharField(max_length=32)),
                ("city_name", models.CharField(max_length=120)),
                ("country", models.CharField(db_index=True, max_length=2)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("population", models.IntegerField(default=0)),
                ("period_kind", models.CharField(choices=[("day", "day"), ("month", "month"), ("year", "year")], max_length=8)),
                ("period_start", models.DateField()),
                ("count", models.IntegerField(default=0)),
                ("good", models.IntegerField(default=0)),
                ("medium", models.IntegerField(default=0)),
                ("bad", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["period_kind", "period_start"], name="lightning_c_period__91ca91_idx"),
                    models.Index(fields=["country", "period_kind", "period_start"], name="lightning_c_country_36a6ee_idx"),
                    models.Index(fields=["city_id", "period_kind", "period_start"], name="lightning_c_city_id_bf97f9_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("city_id", "period_kind", "period_start"), name="uniq_city_period"),
                ],
            },
        ),
    ]
