# Generated by Django 6.0.6 on 2026-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strikebet',
            name='outcome',
            field=models.CharField(blank=True, choices=[('won', 'won'), ('lost', 'lost'), ('push', 'push')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='strikebet',
            name='scope_kind',
            field=models.CharField(choices=[('globe', 'globe'), ('country', 'country')], max_length=8),
        ),
        migrations.AlterField(
            model_name='strikebet',
            name='side',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=4),
        ),
        migrations.AlterField(
            model_name='strikebet',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('settled', 'settled')], db_index=True, default='pending', max_length=8),
        ),
    ]
