# Generated by Django 6.0.6 on 2026-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_player_grid_elo_gridmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmatch',
            name='area_max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='area_max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='area_min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='area_min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='cell_size_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='model_name',
            field=models.CharField(default='EAGZ-1', max_length=20),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='model_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='zone_h_norm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gridmatch',
            name='zone_round_strikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gridmatch',
            name='grid_cols',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='gridmatch',
            name='grid_rows',
            field=models.IntegerField(default=8),
        ),
    ]
