# Generated by Django 6.0.6 on 2026-07-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_gridmatch_area_max_lat_gridmatch_area_max_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCellSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('player', 'player'), ('bot', 'bot')], max_length=6)),
                ('cell', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='account.gridmatch')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'actor', 'started_at'], name='account_gri_match_i_33a610_idx')],
            },
        ),
    ]
