# Generated by Django 6.0.6 on 2026-06-15 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], db_index=True, default='active', max_length=12)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'ends_at'], name='game_gamero_status_24b1c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=32)),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('locked_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('strikes_captured', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='game.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'user'], name='game_pick_round_i_059f27_idx'), models.Index(fields=['finalized', 'expires_at'], name='game_pick_finaliz_714270_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='XX', max_length=2)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('total_strikes_captured', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['games_won'], name='game_player_games_w_687fb3_idx'), models.Index(fields=['games_played'], name='game_player_games_p_249d3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('won', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gameround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'points'], name='game_roundr_round_i_cd3279_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'user'), name='uniq_round_user')],
            },
        ),
    ]
